### ISSUE TITLE
Syntax highlighting fails after "#!**/somefolder/somefile.txt"

### ISSUE THREAD

**Issue by ageoghegan** [bsara/language-gitignore#5] opened 2016-08-17 09:59 UTC
```
!**/packages/build/
# Uncomment if necessary however generally it will be regenerated when needed
#!**/packages/repositories.config
# NuGet v3's project.json files produces more ignoreable files
```

You'll see the last line in this example is never syntax highlighted properly as the prior line seems to break it.

**Comment by ageoghegan** [comment] 2016-08-17 10:00
Sorry that comment text got interpreted somehow as Header text.  I'll try wrapping it in a code segment
`
!**/packages/build/
# Uncomment if necessary however generally it will be regenerated when needed
#!**/packages/repositories.config
# NuGet v3's project.json files produces more ignoreable files
`

**Comment by ageoghegan** [comment] 2016-08-17 10:03
Okay this is not working as expected.  There's no way to write raw text without the markdown post processor monkeying with it.  I'll attach a raw text file.
[gitignore.txt](https://github.com/bsara/language-gitignore/files/422272/gitignore.txt)

**Comment by bsara** [comment] 2016-10-13 19:35
Thanks @ageoghegan for letting me know. Sorry that I've taken so long to even acknowledge this issue being posted. I'm hoping to take a look very soon. Also, thanks for the example file, that's very helpful.

**Comment by bsara** [comment] 2016-10-13 19:37
after looking at the other issues sumbitted, this seems to be a duplicate of #4. refer to that issue for future updates.

**Closed as completed by bsara** 2016-10-13 19:37 UTC
Labels: bug, duplicate
